# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-strict

from typing import SupportsIndex

import torch

class RdmaMemoryView:
    def size(self) -> int: ...

class RdmaMemoryMutableView:
    def size(self) -> int: ...

class RdmaRemoteBuffer:
    def __init__(self, ptr: int, len: int, access_key: str) -> None: ...
    def __getstate__(self) -> tuple[int, int, str]: ...
    def __reduce__(self) -> tuple[object, tuple[int, int, str]]: ...
    def __reduce_ex__(
        self, protocol: SupportsIndex
    ) -> tuple[object, tuple[int, int, str]]: ...

class RdmaMemory:
    def __init__(self, tensor: torch.Tensor) -> None: ...
    def to_view(
        self, offset: int | None = None, length: int | None = None
    ) -> RdmaMemoryView: ...
    def to_mutable_view(
        self, offset: int | None = None, length: int | None = None
    ) -> RdmaMemoryMutableView: ...
    def to_remote_buffer(self) -> RdmaRemoteBuffer: ...
    def reused_registration(self) -> bool: ...

class RdmaTransport:
    def __init__(self, device: torch.device) -> None: ...
    @staticmethod
    def supported() -> bool: ...
    def bind(self) -> bytes: ...
    def connect(self, peer_url: bytes) -> int: ...
    def connected(self) -> bool: ...
    def write(
        self, local_buffer: RdmaMemoryView, remote_buffer: RdmaRemoteBuffer
    ) -> int: ...
    def read(
        self, local_buffer: RdmaMemoryMutableView, remote_buffer: RdmaRemoteBuffer
    ) -> int: ...
