# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-strict

import torch

class RdmaMemoryView:
    def size(self) -> int: ...

class RdmaMemoryMutableView: ...

class RdmaRemoteBuffer:
    def __getstate__(self) -> tuple[int, str]: ...
    def __setstate__(self, state: tuple[int, str]) -> None: ...

class RdmaMemory:
    def __init__(self, tensor: torch.Tensor) -> None: ...
    def to_view(self) -> RdmaMemoryView: ...
    def to_mutable_view(self) -> RdmaMemoryMutableView: ...
    def to_remote_buffer(self) -> RdmaRemoteBuffer: ...

class RdmaTransport:
    def __init__(self, device: torch.device) -> None: ...
    @staticmethod
    def supported() -> bool: ...
    def bind(self) -> bytes: ...
    def connect(self, peer_url: bytes) -> int: ...
    def connected(self) -> bool: ...
    def write(
        self, local_buffer: RdmaMemoryView, remote_buffer: RdmaRemoteBuffer
    ) -> int: ...
    def read(
        self, local_buffer: RdmaMemoryMutableView, remote_buffer: RdmaRemoteBuffer
    ) -> int: ...
