# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-strict

from typing import Any

import torch

class ErrCode:
    NotImplemented: ErrCode
    DriverError: ErrCode
    TopologyDisconnect: ErrCode
    InvalidArgument: ErrCode
    NotConnected: ErrCode
    TransportError: ErrCode
    ConnectionFailed: ErrCode
    MemoryRegistrationError: ErrCode
    Timeout: ErrCode
    ResourceExhausted: ErrCode
    @property
    def value(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class MemoryType:
    DRAM: MemoryType
    VRAM: MemoryType
    NVME: MemoryType
    @property
    def value(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class TransportType:
    NVLink: TransportType
    RDMA: TransportType
    TCP: TransportType
    @property
    def value(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Err:
    @property
    def code(self) -> ErrCode: ...
    @property
    def message(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Result:
    def has_value(self) -> bool: ...
    def has_error(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def value(self) -> Any: ...
    def error(self) -> Err: ...

class TransportFuture:
    def done(self) -> bool: ...
    def get(self) -> Result: ...
    def wait_for(self, timeout_ms: int) -> bool: ...

class Segment:
    def __init__(
        self,
        ptr: int,
        length: int,
        mem_type: MemoryType = ...,
        device_id: int = ...,
    ) -> None: ...
    @property
    def data_ptr(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def mem_type(self) -> MemoryType: ...
    @property
    def device_id(self) -> int: ...

class RegisteredSegmentSpan:
    @property
    def size(self) -> int: ...

class RegisteredSegment:
    def export_id(self) -> Result: ...
    def span(self, offset: int, length: int) -> RegisteredSegmentSpan: ...
    @property
    def length(self) -> int: ...

class RemoteRegisteredSegmentSpan:
    @property
    def size(self) -> int: ...

class RemoteRegisteredSegment:
    def span(self, offset: int, length: int) -> RemoteRegisteredSegmentSpan: ...
    @property
    def length(self) -> int: ...

class TransferRequest:
    def __init__(
        self,
        local: RegisteredSegmentSpan,
        remote: RemoteRegisteredSegmentSpan,
    ) -> None: ...

class RequestOptions:
    def __init__(
        self,
        stream: int | None = None,
        timeout_ms: int | None = None,
    ) -> None: ...

class MultiTransportFactory:
    def __init__(self, device_id: int) -> None: ...
    def register_segment(self, segment: Segment) -> Result: ...
    def import_segment(self, export_id: bytes) -> Result: ...
    def create_transport(self, peer_topology: bytes) -> Result: ...
    def get_topology(self) -> bytes: ...

class MultiTransport:
    def bind(self) -> Result: ...
    def connect(self, info: bytes) -> Result: ...
    def put(
        self,
        requests: list[TransferRequest],
        options: RequestOptions = ...,
    ) -> TransportFuture: ...
    def get(
        self,
        requests: list[TransferRequest],
        options: RequestOptions = ...,
    ) -> TransportFuture: ...
    def transfer_count(self, transport_type: TransportType) -> int: ...
    def shutdown(self) -> None: ...
