#!/bin/bash
# =============================================================================
# rcclx_remerge.sh — Reapply rcclx Meta customizations onto feb drop upstream
# =============================================================================
#
# Uses the two rcclx commits to perform the merge automatically:
#
#   PRE  = parents(4acd7e79b385) — old rcclx WITH Meta customizations
#   POST = 4acd7e79b385          — new rcclx AFTER feb drop (upstream, no Meta)
#
#   diff(POST, PRE) gives:
#     (+) lines: Meta customizations that were LOST   → add back automatically
#     (-) lines: Upstream feb drop additions to KEEP  → leave alone
#
# Merge strategy for each file:
#   1. Extract pure (+) hunks (Meta customizations) from diff(POST, PRE)
#   2. Apply them as a patch to POST in the working tree
#   3. If patch applies cleanly → done (auto-merged)
#   4. If mixed hunks or patch rejects → vimdiff for manual resolution
#
# Usage:
#   bash rcclx_remerge.sh                  # process all 53 files
#   bash rcclx_remerge.sh --file <relpath> # process one file
#   bash rcclx_remerge.sh --dry-run        # show what would happen, no writes
#   bash rcclx_remerge.sh --from <file>    # resume from a specific file
#
# =============================================================================

set -euo pipefail

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------
FBSOURCE="/data/users/srinathb/fbsource"
cd "$FBSOURCE"

PRE_REV="parents(4acd7e79b385)"   # old rcclx with Meta customizations
POST_REV="4acd7e79b385"           # new rcclx (feb drop, no Meta)
RCCLX_SRC="fbcode/comms/rcclx/develop/projects/rccl/src"
RCCLX_WORKDIR="$FBSOURCE/$RCCLX_SRC"

MERGE_TOOL="${MERGE_TOOL:-vimdiff}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="/tmp/rcclx_remerge_${TIMESTAMP}.log"
TMPDIR_MERGE="/tmp/rcclx_remerge_$$"
mkdir -p "$TMPDIR_MERGE"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

# --------------------------------------------------------------------------
# Embedded Python hunk filter
# Reads diff(POST, PRE) from stdin and:
#   - Outputs ONLY pure (+) hunks as a patch (Meta customizations to restore)
#   - Skips pure (-) hunks (upstream additions already in POST — leave alone)
#   - Marks mixed hunks as needing manual resolution
# Exit code 0 = all hunks auto-applied; 1 = mixed hunks need manual resolution
# --------------------------------------------------------------------------
HUNK_FILTER=$(cat << 'PYEOF'
import sys, re

def parse_diff(text):
    header, hunks = [], []
    cur = None
    for line in text.splitlines(keepends=True):
        if line.startswith(('--- ', '+++ ')):
            header.append(line)
        elif line.startswith('@@'):
            if cur: hunks.append(cur)
            cur = {'hdr': line, 'lines': []}
        elif cur is not None:
            cur['lines'].append(line)
    if cur: hunks.append(cur)
    return header, hunks

def classify(hunk):
    has_add = any(l.startswith('+') for l in hunk['lines'])
    has_del = any(l.startswith('-') for l in hunk['lines'])
    if has_add and not has_del: return 'add'   # Meta customization → apply
    if has_del and not has_add: return 'del'   # upstream addition  → skip
    return 'mixed'                              # conflict           → manual

header, hunks = parse_diff(sys.stdin.read())
classified = [(h, classify(h)) for h in hunks]

auto  = [h for h, k in classified if k == 'add']
skip  = [h for h, k in classified if k == 'del']
mixed = [h for h, k in classified if k == 'mixed']

# Emit filterd patch: header + only the pure-addition hunks
sys.stdout.write(''.join(header))
for h in auto:
    sys.stdout.write(h['hdr'])
    sys.stdout.write(''.join(h['lines']))

# Report to stderr
print(f"auto={len(auto)} skip(upstream)={len(skip)} manual={len(mixed)}", file=sys.stderr)

sys.exit(1 if mixed else 0)
PYEOF
)

# --------------------------------------------------------------------------
# Parse arguments
# --------------------------------------------------------------------------
SINGLE_FILE=""
DRY_RUN=false
RESUME_FROM=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --file)    SINGLE_FILE="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true;     shift   ;;
    --from)    RESUME_FROM="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1    ;;
  esac
done

# --------------------------------------------------------------------------
# File list — 124 files with confirmed lost customizations, sorted by
# deletion count (highest impact first). Generated by full_audit.sh.
# --------------------------------------------------------------------------
ALL_FILES=(
  # P0: Largest deletion counts — core algorithm/performance files
  "graph/tuning.cc"                               # del=434
  "device/symmetric/primitives.cuh"               # del=418
  "init.cc"                                       # del=340
  "enqueue.cc"                                    # del=336
  "collectives.cc"                                # del=324
  "nccl.h"                                        # del=189 (NEWLY DISCOVERED)
  "rccl.h"                                        # del=185 (NEWLY DISCOVERED)
  "nccl.h.in"                                     # del=181 (NEWLY DISCOVERED)
  "include/comm.h"                                # del=140
  "transport/net_ib.cc"                           # del=137
  "register/register.cc"                          # del=136, add=0 — FULLY OVERWRITTEN
  "device/symmetric/all_gather.cuh"               # del=128 (NEWLY DISCOVERED)
  "group.cc"                                      # del=121
  "graph/topo.cc"                                 # del=120
  "transport/net.cc"                              # del=116
  "device/symmetric/reduce_scatter.cuh"           # del=113 (NEWLY DISCOVERED)
  "device/reduce_scatter.h"                       # del=94
  "transport/nvls.cc"                             # del=91
  "graph/topo.h"                                  # del=90
  "transport/p2p.cc"                              # del=87
  "plugin/profiler.cc"                            # del=72 (NEWLY DISCOVERED)
  "allocator.cc"                                  # del=63
  "rccl_wrap.cc"                                  # del=59
  "include/cpuset.h"                              # del=45 (NEWLY DISCOVERED)
  "misc/proxy_trace/proxy_trace.cc"               # del=42 (NEWLY DISCOVERED)
  "include/device.h"                              # del=35
  "transport/net_socket.cc"                       # del=29 (NEWLY DISCOVERED)
  "transport/coll_net.cc"                         # del=29
  "plugin/plugin_open.cc"                         # del=29 (NEWLY DISCOVERED)
  "include/proxy_trace/proxy_trace.h"             # del=29 (NEWLY DISCOVERED)
  "plugin/net.cc"                                 # del=28 (NEWLY DISCOVERED)
  "device/common.h"                               # del=28
  "proxy.cc"                                      # del=27
  "graph/connect.cc"                              # del=27
  "include/nccl_common.h"                         # del=26
  "include/nvtx.h"                                # del=25 (NEWLY DISCOVERED)
  "misc/param.cc"                                 # del=22 (NEWLY DISCOVERED)
  "graph/rome_models.cc"                          # del=22 (NEWLY DISCOVERED)
  "graph/xml.cc"                                  # del=21
  "misc/shmutils.cc"                              # del=20
  "device/symmetric/generate.py"                  # del=19 (NEWLY DISCOVERED)
  "include/register.h"                            # del=18 (NEWLY DISCOVERED)
  "misc/mlx5dvwrap.cc"                            # del=16 (NEWLY DISCOVERED)
  "include/proxy.h"                               # del=16
  "bootstrap.cc"                                  # del=15
  "include/api_trace.h"                           # del=14 (NEWLY DISCOVERED)
  "include/register_inline.h"                     # del=13 (NEWLY DISCOVERED)
  "device/generate.py"                            # del=13
  "device/symmetric/kernel.cuh"                   # del=12 (NEWLY DISCOVERED)
  "device/common.cu"                              # del=12
  "plugin/net/net_v9.cc"                          # del=11 (NEWLY DISCOVERED)
  "misc/api_trace.cc"                             # del=11
  "include/plugin/nccl_profiler.h"                # del=11 (NEWLY DISCOVERED)
  "include/alloc.h"                               # del=11 (NEWLY DISCOVERED)
  "device/prims_simple.h"                         # del=11
  "misc/latency_profiler/CollTraceFunc.cc"        # del=10 (NEWLY DISCOVERED)
  "include/plugin/nccl_net.h"                     # del=10 (NEWLY DISCOVERED)
  "graph/paths.cc"                                # del=10
  "plugin/net/net_v8.cc"                          # del=9  (NEWLY DISCOVERED)
  "plugin/net/net_v7.cc"                          # del=9  (NEWLY DISCOVERED)
  "plugin/net/net_v6.cc"                          # del=9  (NEWLY DISCOVERED)
  "plugin/tuner.cc"                               # del=8  (NEWLY DISCOVERED)
  "include/transport.h"                           # del=8
  "misc/cudawrap.cc"                              # del=7  (NEWLY DISCOVERED)
  "include/nvtx_payload_schemas.h"                # del=7  (NEWLY DISCOVERED)
  "include/bitops.h"                              # del=7  (NEWLY DISCOVERED)
  "device/msccl_kernel_impl.h"                    # del=7
  "ras/ras.cc"                                    # del=5  (NEWLY DISCOVERED)
  "plugin/tuner/tuner_v2.cc"                      # del=5  (NEWLY DISCOVERED)
  "plugin/net/net_v10.cc"                         # del=5  (NEWLY DISCOVERED)
  "misc/strongstream.cc"                          # del=5  (NEWLY DISCOVERED)
  "misc/alt_rsmi.cc"                              # del=5  (NEWLY DISCOVERED)
  "include/rocmwrap.h"                            # del=5  (NEWLY DISCOVERED)
  "plugin/tuner/tuner_v3.cc"                      # del=4  (NEWLY DISCOVERED)
  "misc/rocmwrap.cc"                              # del=4  (NEWLY DISCOVERED)
  "misc/msccl/msccl_lifecycle.cc"                 # del=4
  "device/all_gather.h"                           # del=4
  "register/coll_reg.cc"                          # del=3  (NEWLY DISCOVERED)
  "plugin/tuner/tuner_v4.cc"                      # del=3  (NEWLY DISCOVERED)
  "plugin/profiler/profiler_v4.cc"                # del=3  (NEWLY DISCOVERED)
  "plugin/profiler/profiler_v3.cc"                # del=3  (NEWLY DISCOVERED)
  "plugin/profiler/profiler_v2.cc"                # del=3  (NEWLY DISCOVERED)
  "plugin/profiler/profiler_v1.cc"                # del=3  (NEWLY DISCOVERED)
  "Makefile"                                      # del=3  (NEWLY DISCOVERED)
  "include/rccl_common.h"                         # del=3
  "include/plugin/net/net_v9.h"                   # del=3  (NEWLY DISCOVERED)
  "include/plugin/net/net_v10.h"                  # del=3  (NEWLY DISCOVERED)
  "include/gdrwrap.h"                             # del=3  (NEWLY DISCOVERED)
  "include/channel.h"                             # del=3
  "device/prims_ll.h"                             # del=3
  "misc/utils.cc"                                 # del=2
  "misc/socket.cc"                                # del=2
  "misc/ibvwrap.cc"                               # del=2  (NEWLY DISCOVERED)
  "misc/gdrwrap.cc"                               # del=2  (NEWLY DISCOVERED)
  "include/shmutils.h"                            # del=2  (NEWLY DISCOVERED)
  "include/plugin/nccl_tuner.h"                   # del=2  (NEWLY DISCOVERED)
  "include/net_device.h"                          # del=2  (NEWLY DISCOVERED)
  "include/allocator.h"                           # del=2  (NEWLY DISCOVERED)
  "device/prims_ll128.h"                          # del=2
  "device/Makefile"                               # del=2  (NEWLY DISCOVERED)
  "debug.cc"                                      # del=2  (NEWLY DISCOVERED)
  "transport/profiler.cc"                         # del=1  (NEWLY DISCOVERED)
  "transport/generic.cc"                          # del=1
  "register/sendrecv_reg.cc"                      # del=1  (NEWLY DISCOVERED)
  "mnnvl.cc"                                      # del=1  (NEWLY DISCOVERED)
  "misc/roctx.cc"                                 # del=1  (NEWLY DISCOVERED)
  "misc/rocm_smi_wrap.cc"                         # del=1
  "include/rocm_smi_wrap.h"                       # del=1  (NEWLY DISCOVERED)
  "include/nvtx3/nvtxDetail/nvtxExtTypes.h"       # del=1  (NEWLY DISCOVERED)
  "include/nvtx3/nvtxDetail/nvtxExtPayloadTypeInfo.h"        # del=1
  "include/nvtx3/nvtxDetail/nvtxExtPayloadHelperInternal.h"  # del=1
  "include/nvtx3/nvtxDetail/nvtxExtImpl.h"        # del=1
  "include/nvtx3/nvtxDetail/nvtxExtImplCounters_v1.h"        # del=1
  "include/nvtx3/nvtxDetail/nvtxExtHelperMacros.h"           # del=1
  "include/nvtx3/nvToolsExtSemanticsScope.h"      # del=1
  "include/nvtx3/nvToolsExtSemanticsCounters.h"   # del=1
  "include/nvtx3/nvToolsExtCounters.h"            # del=1
  "include/msccl/msccl_kernel.h"                  # del=1
  "include/graph.h"                               # del=1
  "include/coll_net.h"                            # del=1  (NEWLY DISCOVERED)
  "include/collectives.h"                         # del=1
  "device/reduce_kernel.h"                        # del=1
  "device/alltoall_pivot.h"                       # del=1  (NEWLY DISCOVERED)
  "device/all_reduce.h"                           # del=1
)

FILES=("${SINGLE_FILE:-}")
[ -z "${SINGLE_FILE:-}" ] && FILES=("${ALL_FILES[@]}")

# --------------------------------------------------------------------------
# Header
# --------------------------------------------------------------------------
TOTAL=${#FILES[@]}
echo -e "${BOLD}================================================================${NC}"
echo -e "${BOLD} RCCLX CUSTOMIZATION REMERGE${NC}"
echo -e "${BOLD}================================================================${NC}"
echo -e " PRE  (old rcclx, has Meta): ${PRE_REV}"
echo -e " POST (feb drop, no Meta):   ${POST_REV}"
echo -e " Files to process:           ${TOTAL}"
echo -e " Log:                        ${LOG_FILE}"
if $DRY_RUN; then echo -e " ${YELLOW}Mode: DRY RUN — no files written${NC}"; fi
echo -e "${BOLD}================================================================${NC}"
echo ""
echo "$(date) — PRE=$PRE_REV  POST=$POST_REV" > "$LOG_FILE"
echo "" >> "$LOG_FILE"

# --------------------------------------------------------------------------
# Counters
# --------------------------------------------------------------------------
COUNT=0; AUTO=0; MANUAL=0; IDENTICAL=0; SKIPPED=0
RESUMING=true; [ -z "$RESUME_FROM" ] && RESUMING=false
declare -a MANUAL_FILES=() SKIPPED_FILES=()

# --------------------------------------------------------------------------
# Main loop
# --------------------------------------------------------------------------
for f in "${FILES[@]}"; do

  # Resume support
  if $RESUMING; then
    [ "$f" = "$RESUME_FROM" ] && RESUMING=false || continue
  fi

  COUNT=$((COUNT + 1))
  slug=$(echo "$f" | tr '/' '_')
  PRE_F="$TMPDIR_MERGE/pre_${slug}"
  POST_F="$TMPDIR_MERGE/post_${slug}"
  PATCH_F="$TMPDIR_MERGE/patch_${slug}.diff"
  AUTO_PATCH_F="$TMPDIR_MERGE/auto_${slug}.diff"
  DEST="$RCCLX_WORKDIR/$f"

  echo -e "${BLUE}${BOLD}[$COUNT/$TOTAL] $f${NC}"

  # Extract file at both revisions from the same rcclx path
  sl cat -r "$PRE_REV"  "$RCCLX_SRC/$f" > "$PRE_F"  2>/dev/null || true
  sl cat -r "$POST_REV" "$RCCLX_SRC/$f" > "$POST_F" 2>/dev/null || true

  # ---- Guards -------------------------------------------------------------
  if [ ! -s "$PRE_F" ] && [ ! -s "$POST_F" ]; then
    echo -e "  ${YELLOW}SKIP — absent at both revisions${NC}"
    SKIPPED=$((SKIPPED+1)); SKIPPED_FILES+=("$f")
    echo "SKIP: $f" >> "$LOG_FILE"; continue
  fi

  if [ ! -s "$PRE_F" ]; then
    echo -e "  ${CYAN}NEW — added by feb drop; keeping as-is${NC}"
    IDENTICAL=$((IDENTICAL+1)); echo "NEW_FILE: $f" >> "$LOG_FILE"; continue
  fi

  if [ ! -s "$POST_F" ]; then
    echo -e "  ${YELLOW}DELETED — feb drop removed it; restoring from PRE${NC}"
    if ! $DRY_RUN; then mkdir -p "$(dirname "$DEST")"; cp "$PRE_F" "$DEST"; fi
    AUTO=$((AUTO+1)); echo "RESTORED_DELETED: $f" >> "$LOG_FILE"; continue
  fi

  # ---- No diff → nothing to do -------------------------------------------
  if diff -q "$PRE_F" "$POST_F" > /dev/null 2>&1; then
    echo -e "  ${GREEN}IDENTICAL — no customizations to restore${NC}"
    IDENTICAL=$((IDENTICAL+1)); echo "IDENTICAL: $f" >> "$LOG_FILE"; continue
  fi

  # ---- Generate diff(POST → PRE):
  #      (+) lines = Meta customizations to add back
  #      (-) lines = upstream feb drop additions to leave alone
  diff -u "$POST_F" "$PRE_F" > "$PATCH_F" 2>/dev/null || true

  # ---- Classify hunks with embedded Python filter -------------------------
  FILTER_STDERR="$TMPDIR_MERGE/filter_${slug}.log"
  if python3 -c "$HUNK_FILTER" < "$PATCH_F" > "$AUTO_PATCH_F" 2>"$FILTER_STDERR"; then
    HAS_MIXED=false
  else
    HAS_MIXED=true
  fi
  HUNK_STATS=$(cat "$FILTER_STDERR")

  if $DRY_RUN; then
    echo -e "  ${CYAN}DRY RUN: $HUNK_STATS${NC}"
    if $HAS_MIXED; then
      echo -e "  ${YELLOW}Mixed hunks found — would need manual resolution${NC}"
    fi
    echo "DRY_RUN: $f ($HUNK_STATS)" >> "$LOG_FILE"
    echo ""; continue
  fi

  # ---- Apply the auto-patch (pure Meta customization hunks) ---------------
  cp "$POST_F" "$DEST"   # start from POST (has upstream changes)
  PATCH_REJECTS=false
  REJ_F="${DEST}.rej"

  if [ -s "$AUTO_PATCH_F" ]; then
    # Apply with fuzz=3 to tolerate minor context shifts from upstream changes
    if ! patch --fuzz=3 --quiet "$DEST" < "$AUTO_PATCH_F" 2>/dev/null; then
      PATCH_REJECTS=true
    fi
  fi

  # ---- Determine outcome --------------------------------------------------
  if ! $HAS_MIXED && ! $PATCH_REJECTS; then
    # All Meta customizations applied cleanly, no manual work needed
    echo -e "  ${GREEN}AUTO-MERGED: $HUNK_STATS${NC}"
    rm -f "$REJ_F"
    AUTO=$((AUTO+1)); echo "AUTO_MERGED: $f ($HUNK_STATS)" >> "$LOG_FILE"

  else
    # Some hunks couldn't be auto-applied — need manual resolution
    REASON=""
    $HAS_MIXED     && REASON+="mixed hunks"
    $PATCH_REJECTS && REASON+="${REASON:+, }patch rejects"
    echo -e "  ${YELLOW}PARTIAL AUTO-MERGE: $HUNK_STATS — $REASON${NC}"
    echo -e "  ${YELLOW}Opening vimdiff: LEFT=PRE (old rcclx), RIGHT=DEST (partially merged)${NC}"
    echo -e "  ${YELLOW}Copy remaining Meta customizations from LEFT into RIGHT, then :wqa${NC}"

    # Show reject summary if any
    if [ -f "$REJ_F" ]; then
      echo ""
      echo -e "  ${RED}Rejected hunks (in ${REJ_F}):${NC}"
      grep "^@@" "$REJ_F" | head -10 | sed 's/^/    /'
      echo ""
    fi

    read -rp "  Press Enter to open vimdiff, or 's' to skip, 'q' to quit: " resp
    case "$resp" in
      s|S) echo -e "  ${YELLOW}SKIPPED${NC}"; SKIPPED=$((SKIPPED+1)); SKIPPED_FILES+=("$f")
           echo "SKIPPED_MANUAL: $f" >> "$LOG_FILE"; echo ""; continue ;;
      q|Q) echo -e "${YELLOW}Quitting — resume with: --from $f${NC}"
           echo "QUIT_AT: $f" >> "$LOG_FILE"; break ;;
    esac

    $MERGE_TOOL "$PRE_F" "$DEST" || true
    rm -f "$REJ_F"
    MANUAL=$((MANUAL+1)); MANUAL_FILES+=("$f")
    echo "MANUAL_MERGED: $f ($HUNK_STATS, reason=$REASON)" >> "$LOG_FILE"
    echo -e "  ${GREEN}Done${NC}"
  fi

  echo ""
done

# --------------------------------------------------------------------------
# Cleanup
# --------------------------------------------------------------------------
rm -rf "$TMPDIR_MERGE"

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------
echo ""
echo -e "${BOLD}================================================================${NC}"
echo -e "${BOLD} REMERGE COMPLETE${NC}"
echo -e "${BOLD}================================================================${NC}"
echo -e " ${GREEN}Auto-merged:${NC}         $AUTO"
echo -e " ${CYAN}Manual (vimdiff):${NC}    $MANUAL"
echo -e " ${CYAN}Identical (skipped):${NC} $IDENTICAL"
echo -e " ${YELLOW}Skipped:${NC}             $SKIPPED"
echo -e " Total processed:    $COUNT / $TOTAL"
echo ""
if [ ${#MANUAL_FILES[@]} -gt 0 ]; then
  echo -e " ${CYAN}Files merged via vimdiff:${NC}"; for f in "${MANUAL_FILES[@]}"; do echo "   ✓ $f"; done; echo ""
fi
if [ ${#SKIPPED_FILES[@]} -gt 0 ]; then
  echo -e " ${YELLOW}Skipped (need attention):${NC}"; for f in "${SKIPPED_FILES[@]}"; do echo "   ✗ $f"; done
  echo -e "\n  Resume: ${BOLD}bash rcclx_remerge.sh --from ${SKIPPED_FILES[0]}${NC}"; echo ""
fi
echo " Log: $LOG_FILE"
echo ""
echo -e "${BOLD} Validate:${NC}  bash fbcode/comms/rcclx/audit_rcclx.sh"
echo -e "${BOLD} Review:${NC}    sl diff $RCCLX_SRC/"
echo -e "${BOLD} Build:${NC}     buck2 build fbcode/comms/rcclx/..."
echo -e "${BOLD} Commit:${NC}    sl amend"
echo -e "${BOLD}================================================================${NC}"
