// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

#include "comms/utils/PrecisionClock.h"

#include <cstdlib>

// Use abseil's LOG macros instead of folly's XLOG — keeps PrecisionClock
// buildable from feedstocks (telemetry_stream, hrdw_ring_buffer) that
// don't pull folly in. absl::log is linked by every consumer that
// already uses GpuClockCalibration / EnvUtils.
#include "absl/log/log.h" // @manual=fbsource//third-party/abseil-cpp:log

#include "comms/utils/EnvUtils.h"

// nccl_cvars.h is generated by the internal ncclx-cvars Buck target and is
// absent from both the torchcomms OSS build tree and the hrdw_ring_buffer
// conda feedstock build. Gate it like fbclock below.
#if __has_include("comms/utils/cvars/nccl_cvars.h")
#include "comms/utils/cvars/nccl_cvars.h" // @manual=fbcode//comms/utils/cvars:ncclx-cvars
#else
inline constexpr bool NCCL_USE_PTP_DEFAULT_LITERAL = true;
#endif

// fbclock is a Meta-internal header. The torchcomms OSS build copies
// only fbcode/comms (and ynl) into its build tree, and the
// telemetry_stream / hrdw_ring_buffer conda feedstocks only stage
// fbcode/comms/utils — neither has fbclock on the include path. Gate
// on `__has_include` so a single source compiles in all three contexts
// without a per-build preprocessor flag: the Buck build sees the header
// + links fbclock_c, the OSS / feedstock builds skip the branch and
// fall back to std::chrono::system_clock.
//
// COMMS_NO_FBCLOCK is an explicit opt-out for builds where fbclock.h IS
// reachable via the include path (e.g. the RCCLX cmake/conda build adds
// `-I fbcode`, so __has_include would otherwise be true) but fbclock_c
// is NOT linked. Without this the build links a librccl.so with
// undefined fbclock_init/fbclock_gettime_utc and PyTorch's dlopen fails.
#if defined(COMMS_NO_FBCLOCK)
#define COMMS_HAS_FBCLOCK 0
#elif __has_include("time/fbclock/fbclock.h")
#include "time/fbclock/fbclock.h"
#define COMMS_HAS_FBCLOCK 1
#else
#define COMMS_HAS_FBCLOCK 0
#endif

namespace meta::comms {

namespace {

bool isPtpEnabled() {
  // Inline env read with the cvar yaml's default literal as the
  // fallback — we don't go through the runtime cvar machinery because
  // PrecisionClock initializes lazily on first call to precisionNow(),
  // and many of those call paths fire before ncclCvarInit() runs.
  return ::meta::comms::getBoolEnv(
      "NCCL_USE_PTP", NCCL_USE_PTP_DEFAULT_LITERAL);
}

// Process-global handle to fbclock. Initialized exactly once on first
// access; intentionally leaked so the destructor never races with late
// callers during shutdown (mirrors common/time/PTP.cpp's PTPWrapper).
class PrecisionClockImpl {
 public:
  PrecisionClockImpl() : usingPtp_(false) {
    if (!isPtpEnabled()) {
      LOG(INFO) << "PrecisionClock: NCCL_USE_PTP disabled, using system_clock";
      return;
    }
#if COMMS_HAS_FBCLOCK
    int err = fbclock_init(&lib_, FBCLOCK_PATH);
    if (err != FBCLOCK_E_NO_ERROR) {
      LOG(WARNING) << "PrecisionClock: fbclock_init failed (path="
                   << FBCLOCK_PATH << ", err=" << err
                   << "), falling back to system_clock";
      return;
    }
    usingPtp_ = true;
#else
    LOG(INFO) << "PrecisionClock: built without fbclock, using system_clock";
#endif
  }

  bool usingPtp() const noexcept {
    return usingPtp_;
  }

#if COMMS_HAS_FBCLOCK
  // Reads fbclock without holding a mutex. fbclock_gettime_utc mutates
  // lib_.min_phc_delay (a monotonically-decreasing int64) on every call;
  // this is a benign race accepted by common/time/PTP.cpp as well.
  // The shared-memory read uses fbclock's own seqlock/CRC protocol.
  //
  // Uses the UTC variant (not fbclock_gettime, which returns TAI) so the
  // returned ns count is on the same epoch as std::chrono::system_clock —
  // otherwise callers wrapping the result in a system_clock::time_point
  // would land ~37s in the future (current TAI-UTC leap-second offset).
  bool getTruetime(fbclock_truetime* out) noexcept {
    if (!usingPtp_) {
      return false;
    }
    return fbclock_gettime_utc(&lib_, out) == FBCLOCK_E_NO_ERROR;
  }
#endif

  static PrecisionClockImpl& instance() {
    static auto* p = new PrecisionClockImpl();
    return *p;
  }

 private:
#if COMMS_HAS_FBCLOCK
  fbclock_lib lib_{};
#endif
  bool usingPtp_;
};

std::pair<uint64_t, uint64_t> systemClockRangeNs() {
  auto u = static_cast<uint64_t>(
      std::chrono::duration_cast<std::chrono::nanoseconds>(
          std::chrono::system_clock::now().time_since_epoch())
          .count());
  return {u, u};
}

} // namespace

bool precisionUsingPtp() noexcept {
  return PrecisionClockImpl::instance().usingPtp();
}

std::pair<uint64_t, uint64_t> precisionNowRangeNs() noexcept {
#if COMMS_HAS_FBCLOCK
  fbclock_truetime tt{};
  if (PrecisionClockImpl::instance().getTruetime(&tt)) {
    return {tt.earliest_ns, tt.latest_ns};
  }
#endif
  return systemClockRangeNs();
}

uint64_t precisionNowNs() noexcept {
  auto [earliest, latest] = precisionNowRangeNs();
  return earliest + (latest - earliest) / 2;
}

uint64_t precisionErrorNs() noexcept {
  auto [earliest, latest] = precisionNowRangeNs();
  return latest - earliest;
}

std::chrono::system_clock::time_point precisionNow() noexcept {
  return std::chrono::system_clock::time_point{
      std::chrono::nanoseconds{precisionNowNs()}};
}

} // namespace meta::comms
