############################### GENERAL ###############################

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
if(DEFINED ROCPROFILER_PACKAGE_EXTRA_NAME)
    set(CPACK_PACKAGE_NAME "${PROJECT_NAME}-${ROCPROFILER_PACKAGE_EXTRA_NAME}")
endif()
set(CPACK_PACKAGE_VENDOR "Advanced Micro Devices, Inc.")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Rocprof Trace Decoder for AMD Thread Trace data")
set(CPACK_PACKAGE_PROJECT_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_PROJECT_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_PROJECT_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_CONTACT "ROCm Profiler Support <dl.ROCm-Profiler.support@amd.com>")
set(CPACK_RESOURCE_FILE_LICENSE "${TTD_PROJECT_SOURCE_DIR}/LICENSE")

if(DEFINED CPACK_PACKAGE_INSTALL_DIRECTORY)
    set(CPACK_SET_DESTDIR true)
    set(CPACK_INSTALL_PREFIX ${CPACK_PACKAGE_INSTALL_DIRECTORY})
endif()

if(DEFINED ENV{CPACK_PACKAGE_FILE_NAME})
    set(CPACK_PACKAGE_FILE_NAME $ENV{CPACK_PACKAGE_FILE_NAME})
endif()

if(NOT DEFINED CPACK_GENERATOR)
    set(CPACK_GENERATOR "STGZ" "DEB" "RPM" "TGZ")
endif()

set(CPACK_PACKAGE_VERSION
    "${CPACK_PACKAGE_PROJECT_VERSION_MAJOR}.${CPACK_PACKAGE_PROJECT_VERSION_MINOR}.${CPACK_PACKAGE_PROJECT_VERSION_PATCH}"
)

############################### DEBIAN ###############################

## Debian package specific variables
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/ROCm/rocm-systems")

# Enable Component Mode & install settings.
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_RUNTIME_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_DEBIAN_ASAN_PACKAGE_NAME "${PROJECT_NAME}-asan")
set(CPACK_DEBIAN_TESTS_PACKAGE_NAME "${PROJECT_NAME}-tests")

############################### RPM ###############################

# Enable Component Mode & install settings.
set(CPACK_RPM_COMPONENT_INSTALL ON)
set(CPACK_RPM_RUNTIME_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_RPM_ASAN_PACKAGE_NAME "${PROJECT_NAME}-asan")
set(CPACK_RPM_TESTS_PACKAGE_NAME "${PROJECT_NAME}-tests")

include(CPack)
