# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-strict

import torch

class TorchCommNCCLX: ...

class RdmaTransport:
    def __init__(self, device: torch.device) -> None: ...  # pyre-ignore[11]
    @staticmethod
    def supported() -> bool: ...
    def bind(self) -> bytes: ...
    def connect(self, peer_url: bytes) -> int: ...
    def connected(self) -> bool: ...
