# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-strict

import torch

class TorchCommNCCLX: ...

class RdmaMemoryView:
    def size(self) -> int: ...

class RdmaRemoteBuffer: ...

class RdmaMemory:
    def __init__(self, tensor: torch.Tensor) -> None: ...  # pyre-ignore[11]
    def to_view(self) -> RdmaMemoryView: ...
    def to_remote_buffer(self) -> RdmaRemoteBuffer: ...

class RdmaTransport:
    def __init__(self, device: torch.device) -> None: ...  # pyre-ignore[11]
    @staticmethod
    def supported() -> bool: ...
    def bind(self) -> bytes: ...
    def connect(self, peer_url: bytes) -> int: ...
    def connected(self) -> bool: ...
    def write(
        self, local_buffer: RdmaMemoryView, remote_buffer: RdmaRemoteBuffer
    ) -> int: ...
